all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
all_joints_names:
- head_left
- head_right
- neck_mid
- antenna_left
- antenna_right
- antenna_mid
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_yaw_tracker_2022Jun27/yaw_tracker_2022_tarun75shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: /home/tarun/anaconda3/envs/DLC/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_yaw_tracker_2022Jun27/Documentation_data-yaw_tracker_2022_75shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.001
  - 50000
- - 0.0005
  - 100000
- - 0.0001
  - 150000
net_type: resnet_50
num_joints: 6
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
pre_resize: []
project_path: /home/tarun/Desktop/yaw_tracker_2022/yaw_tracker_2022-tarun-2022-06-27
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
